### ISSUE TITLE
error

### ISSUE THREAD

**Issue by francoataffarel** [Areeb297/Data-Collection-Pipeline#1] opened 2022-04-24 19:09 UTC
can u help me ?

 Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

**Comment by Areeb297** [comment] 2022-04-24 19:30
Hi Francoa,

I think if you used the code from my GH repo, you would not that get an
error as the chrome driver is installed in the given directory when the
code is run. Hope this helps.
The code:self.driver = ChromeDriverManager().install()
Regards,
Areeb Shafqat

**Comment by Areeb297** [comment] 2022-04-26 03:04
The issue is closed as either the ChromeDriverManager needs to be in the correct directory, or we can use ChromeDriverManager().install() directly in our script without worrying about this issue

**Closed as completed** 2022-04-26 03:03 UTC
